path_controllers:
    repulsive_controller:
        gravitational_constant:     1.0
        repulsion_exponent:         1.5
        control_frequency:          20.0

        kp_linear:                  20.0
        ki_linear:                  0.0
        kd_linear:                  0.0
        
        kp_angular:                 10.0
        ki_angular:                 1.0
        kd_angular:                 2.0