main_server:
    network:
        tcp_ip:                       192.168.0.1
        tcp_port:                     8000
    
    map_server:
        pixelmap:
            map_bmp_relative_path:        "/data/map/bitmap"
            map_csv_relative_path:        "/data/map/csv/places.csv"
            map_origin_row:               1175
            map_origin_col:               1470
            map_roi_width:                52.755
            map_roi_height:               34.82
            map_pad_radius:               0.15
            
    
    filesystem:
        base_dir:                     ""

robot_system:
    robot_info:
      - robot_id:                     0
        robot_type:                   postman
        robot_name:                   postman_1
        robot_tcp_ip:                 "0.0.0.0"
        robot_tcp_port:               8000

      - robot_id:                     1
        robot_type:                   postman
        robot_name:                   postman_2
        robot_tcp_ip:                 "0.0.0.0"
        robot_tcp_port:               8000

      - robot_id:                     2
        robot_type:                   postman
        robot_name:                   postman_3
        robot_tcp_ip:                 "0.0.0.0"
        robot_tcp_port:               8000

      - robot_id:                     3
        robot_type:                   postman
        robot_name:                   postman_1
        robot_tcp_ip:                 "0.0.0.0"
        robot_tcp_port:               8000